require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'BuildProject' do
  config = use_native_modules!
  
  pod 'GTMSessionFetcher/Core', :modular_headers => true
  pod 'PromotedAIMetricsSDK', :git => 'https://github.com/promotedai/ios-metrics-sdk'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'BuildProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
