name: android_build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install (react-native-metrics)
      run: npm install
    - name: npm install (BuildProject)
      run: npm install
      working-directory: BuildProject
    - name: Run Appium
      run: node_modules/.bin/appium --log-timestamp --log-no-colors > appium.log &
      working-directory: BuildProject
    - name: npm run test
      run: npm run test
      working-directory: BuildProject
      env:
        TEST_PLATFORM: android
