name: ios_build_and_test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        macos: ['macos-13']
        xcode: ['14.3']
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer'
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install (appium)
      run: npm install appium@2.0.0-beta.53 -g
    - name: npm install (react-native-metrics)
      run: npm install
    - name: npm install (TestProject)
      run: npm install
      working-directory: TestProject
    - name: Appium install UIAutomator2
      run: appium driver install uiautomator2
    - name: Appium install XCUITest
      run: appium driver install xcuitest
    - name: Cocoapod install
      run: pod install
      working-directory: TestProject/ios
    - name: Run Appium
      run: yarn start:appium > appium.log &
      working-directory: TestProject
    - name: yarn test:e2e:ios
      run: yarn test:e2e:ios
      working-directory: TestProject
